name: .Net Build Standard

on:
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    
jobs:
  build:
    uses: github-mao-na-massa/pipeline-templates/.github/workflows/dotnet.yml@main
       
